### ISSUE TITLE
Scroll bar missing on sidebar menu

### ISSUE THREAD

**Issue by louishourcade** [awslabs/aws-dataall#120]
### Describe the bug

A customer raised the fact that there is no scroll bar on the left sidebar menu. This is required for better customer experience.

### How to Reproduce

Open data.all, zoom in the page, and you won't see the scroll bar on the left.

### Expected behavior

If all items from the menu cannot appear on the page, there should be a scroll bar to make them accessible

### OS

Linux

### Python version

3.10

### AWS data.all version

1.0.0

**Comment by dlpzx** [comment]
Hello Louis!

When zooming in the expected behavior is to collapse the side bar like here:
![image](https://user-images.githubusercontent.com/71252798/188439294-9943aca1-d553-4900-9d20-dd92c45c5847.png)

In the top left corner, if you click on the 3 stripes icon, the side menu is expanded:

![image](https://user-images.githubusercontent.com/71252798/188439479-88269661-2563-4a73-8ed7-1e7f935dc132.png)

Is this what you are referring to?

**Comment by louishourcade** [comment]
Hello Adriana,
What you describe is what I get when I reduce my window.
But if I'm full screen and start zooming in (157% in the screenshot below), I don't see what you describe.

![image](https://user-images.githubusercontent.com/43200045/189366834-c90acfca-4654-4dee-861a-5274820df0a6.png)

**Comment by dlpzx** [comment]
Understood, the issue is not that the sidebar does not appear, but that it is not scrollable and when we zoom in or open another window like the developer tools, we cannot scroll down the menu. Okey, I'll pick it up
