### ISSUE TITLE
Once revoked share request leads to error when approved again

### ISSUE THREAD

**Issue by degoldner** [awslabs/aws-dataall#233]
### Describe the bug

A share request between cross account which has been approved and then revoked leads to an error when the requester submits the same requests again and it is approved by the owner.

### How to Reproduce

**When**
There was a successful share request which has been submitted and approved between two groups belonging to two different environments represented by different AWS account.
The share request is then revoked by the owner.
The requester then submits this rejected share request again.
The owner approves the share request again

**Then**
The share request fails

In the logs we can find the following error message:
`
CW Logs: /dataall/test/ecs/share-manager
Failed to share table dataall_test_managed_291122_2_utlfth3j from source account xxxx//eu-central-1 with target account xxxx/eu-central-1 due to: Database with name: dataall_test_managed_291122_2_utlfth3j already exists in target account: xxxx in region: eu-central-1
`

### Expected behavior

Submitting and approving a once rejected share request again should lead to the same result as for a new share request.

### OS

AWS deployment

### Python version

3.7

### AWS data.all version

1.0.0

**Comment by noah-paige** [comment]
I have tried to replicate the above error but received the expected behavior from the following steps:
- Creating share requested from ENV B (requester) to ENV A (owner) and approved by ENV A
- ENV A later revoking the existing share request and receiving a `Revoke_Succeeded` Status and ENV B no longer can access the data
- ENV B re-submitting the share request and re-approved by ENV A
- ENV B receiving `Share_Succeeded` status and can access shared data again

Can you provide some additional detail to the above? Did the revoke share delete the shared database on the requester account (ENV B)? Are you using the latest release of the data.all solution?

**Comment by degoldner** [comment]
Hi Noah, 
thanks for looking into this issue!
We are still using the 1.0.0 version of data.all and this might be the reason for the different results here.
We are currently updating our share logic to the newest version of data.all and will test this again on my end.
