### ISSUE TITLE
An error occurred (UnsupportedPricingPlanException) when calling the GenerateEmbedUrlForAnonymousUser operation

### ISSUE THREAD

**Issue by dlpzx** [awslabs/aws-dataall#236]
I was trying to share a QuickSight Dashboard (created in Env A owned by Team A), Team B in Env B has requested for access & granted by Team A, when Team B clicked into the shared dashboard, this error comes up: “An error occurred (UnsupportedPricingPlanException) when calling the GenerateEmbedUrlForAnonymousUser operation: This API action is supported only when the account has an active Capacity Pricing plan.”

![Screenshot 2022-12-02 at 2 19 47 PM](https://user-images.githubusercontent.com/71252798/205577140-73e8bb98-44ed-45ca-b508-f260465fccb6.png)

**Describe the solution you'd like**
I went into Env A’s QuickSight setting, changed it from “Per reader pricing” to “Session capacity pricing” and it works now. Would be great to include this step to the User Guide too (if this is the intended way of setting this up)

![image (32)](https://user-images.githubusercontent.com/71252798/205577155-8f43b013-24b3-436e-835e-f7a19a59f156.png)

**Comment by diandramelo** [comment]
Hello @dlpzx ,

Could you tell me if **sharing dashboards with a "per reader price" subscription is on the roadmap** for data.all? We have a QuickSight usecase with multiple readers, and the "session capacity pricing" subscription is not ideal for us in terms of costs... Although it would be great to have the possibility of providing multiple dashboards in a catalog and make users request access instead of doing the security job ourselves.

Also, recently I have tried to request access of a dashboard (from one of my test users), and the message that appears is "Request send" (screenshot), which seems that the request worked. The problem is that I cannot find it on the "Shares" section of data.all, on both demand account and administrator account.

![image](https://user-images.githubusercontent.com/72493801/220285462-20f43aec-85fa-4dcc-9cfe-04a3ab8509a6.png)

Thanks in advance!
