### ISSUE TITLE
Create Nested Folder within DataAll

### ISSUE THREAD

**Issue by MATTT-P** [awslabs/aws-dataall#309]
We need the ability to create nested-folder within DataAll. Currently we need to visit S3 management Console to create nested-folder.
1. Deep folder structure is required
2. When a folder is created in S3 console, this is not visible in DataAll.

**Comment by dlpzx** [comment]
Hi @MATTT-P, thank you again for raising issues.

### 1. Deep folder structure is required

So regarding the first issue, it is possible to create nested folders in data.all. 
This is how I defined them:
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/71252798/219314911-b159dd24-64ad-4b6f-a408-023a6dbee66d.png">

When I go to the S3 Bucket I can see my 2 subfolders in nested prefixes:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/71252798/219311369-1d4768ca-b8f6-4595-b5ba-1a60ca505419.png">

Is this what you need? If not, please do not hesitate to provide more info about your use-case.

### 2. When a folder is created in S3 console, this is not visible in DataAll.
Yes, this is because a prefix in S3 can also correspond to a Glue table (table in data.all). That's why we do not expose all S3 prefixes to data.all. Also because the first level of prefixes might not be the ones that we want to catalog and share.
If data producers want to see the entire S3 with all prefixes and subprefixes they can directly go to S3 from the UI, but for cataloguing we restrict it to those folders that should be findable and shareable.


That is the reasoning behind the current implementation, but if you have different needs we are open to changes and improvements.

**Comment by dlpzx** [comment]
Closing stale issue. If needed it will be reopened
