### ISSUE TITLE
Better DataAll session Timeout handling

### ISSUE THREAD

**Issue by MATTT-P** [awslabs/aws-dataall#313]
Short user time-out session. We are being logged out of DataAll (roughly 15 mins) and there is no warning or option to extend the session to the user before the system log out the user.

**Comment by dlpzx** [comment]
Hi Matt, thank you for the interest and for the issues you raised :)  I have edited the title of the issue a bit. I believe that in this issue you are asking for 2 things:

### 1. Increase users session duration.

When logging in, users get an access token and ID token that last for 1h, this are the default values for Cognito; but they can be increased to a maximum of 1day. You can check this configuration in the Cognito user pool deployed by data.all:

![image](https://user-images.githubusercontent.com/71252798/219303519-209d4c44-88cf-4ea6-a23b-75e425f9262c.png)

I think your issue comes from the platform being stale for >10 mins of time. In this case something that might be causing those "seems logged out" issues is the time to pause compute capacity in RDS (default for RDS is 5mins, in data.all 10mins). This is set to minimize costs and take advantage of serverless technologies, but the downside is that it takes time to warm up, you can extend the pause something bigger than 10 minutes so it will be warm-up.

![image](https://user-images.githubusercontent.com/71252798/219305494-d315780c-fa75-4ea8-b1e0-74d95bcfc5c2.png)

I am going to do some experimentation on my end to confirm the issue. Let me know if this seems like your issue.

### 2. Better notification or workflow for logged out users

This is definitely an interesting feature that we would include in the open-source repository. You are more than welcome to start developing and we will assist you with any question and with the testing and merging conflicts. Otherwise this is a cool feature, but at the moment we have several items in our backlog so we cannot commit to implement it in the short-term.
