### ISSUE TITLE
dataallPivotRole is not created when we complete deployment and getting error sandbox-graphql is not authorized to perform: sts:AssumeRole 

### ISSUE THREAD

**Issue by vaquarkhan** [awslabs/aws-dataall#361]
### Describe the bug

AssumeRole operation: User: arn:aws:sts::xxxxxxxxxxx:assumed-role/dataall-sandbox-graphql-role/dataall-sandbox-graphql is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxxxxxxx:role/dataallPivotRole

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

Should not give error

### OS

AWS

### Python version

3.8

### AWS data.all version

https://github.com/awslabs/aws-dataall

### Additional context

Deployed data all on AWS and  when try to create environment getting error 

sandbox-graphql is not authorized to perform: sts:AssumeRole

**Comment by dlpzx** [comment]
Hi @vaquarkhan, thanks for raising the issue. The "AssumeRole..." error is actually the expected behavior because the pivotRole is a role created manually prior to linking the environment. You can download the CloudFormation yaml file form the UI and create the pivotRole in the environment account with the externalId and name provided also from the data.all UI.

Initially, we intended customers to manually "approve" the linking of an AWS account with data.all by creating this super role in the environment account. This explicit action ensures control over the accounts that data.all can access. However, customers are already performing this explicit approval when the account is bootstraped trusting the central data.all account. For this reason we are working in including the pivotRole as part of the environment stack which simplifies the process of linking environments (check out this drafted [PR](https://github.com/awslabs/aws-dataall/pull/355)).

Let me know if you need more info

**Comment by dlpzx** [comment]
Closing stale issue. No actions needed
