### ISSUE TITLE
EnvAdmins inconsistency in view

### ISSUE THREAD

**Issue by kasturmp** [awslabs/aws-dataall#386]
### Describe the bug

Envadmins when they don't have organizations permission are not able to see the linked environments in the organizaition view even though it exists.
They can see it when they click environments on left hand side.

### How to Reproduce

Envadmin should either not be able to open organization view or if they are able to open environments should be shown correctly

### Expected behavior

Envadmin should either not be able to open organization view or if they are able to open environments should be shown correctly

### OS

All

### Python version

3.1

### AWS data.all version

v1.3,v1.4

**Comment by dlpzx** [comment]
Hi @kasturmp I think I understood your issue. It is actually something designed this way. If a team is not administrating an organization, it does not have permissions to list the environments in that organization. The reason is that non-orga admins should not see that other environments accounts. But this is a behavior that we can modify. What do you think?
