### ISSUE TITLE
Provide templates for more restricted CDK roles [CDK role permissions are too powerful]

### ISSUE THREAD

**Issue by zsaltys** [awslabs/aws-dataall#452]
Currently when data.all deploys CloudFormation stacks on linked environments it uses a role like this one:
arn:aws:iam::ACC_ID:role/cdk-hnb659fds-cfn-exec-role-ACC_ID-us-east-1

This role has **AdministratorAccess** policy attached. We should lock this role down to only have necessary permissions for data.all to do its tasks like create S3 buckets, glue databases.

**Comment by dlpzx** [comment]
Hi @zsaltys , thanks for opening an issue. We are discussing this issue internally however we do not see a potential security risk from using the default permissions for cdk roles. The worst that can happen is that in a security break, if someone gets access to your data.all central account (very rare event), they will be able to deploy any resource using cdk in the environment accounts. Of course this will incur costs, but it won't mean a security risk. In any case it is an interesting feature and more restricted permissions are always a good idea. So my proposal would be to design the IAM roles needed for a data.all deployment and provide the templates in the data.all code so that customers can use those instead of the default. We will pick this task when bandwidth allows given that there are other security tasks with higher priority

**Comment by dlpzx** [comment]
Just for visibility: This issue is being designed and tested by @manjulaK and team. Once they have completed the design we will work together on adding it to the repo and documentation of data.all

**Comment by anmolsgandhi** [comment]
Closing this issue as it has been delivered as part of v1.6. Please feel free to reopen the issue if you have any more questions or require further assistance.
