### ISSUE TITLE
Renaming "Organisation" to "Domain"

### ISSUE THREAD

**Issue by pascalwhoop** [awslabs/aws-dataall#51]
Would you be open to rename the organisation to "domain" as this seems to be a more common term we've come across at organisations. The "data domain" concept fits better IMO.

**Comment by louishourcade** [comment]
Hello,
An **Organisation** in data.all is just of group of **Environments**. An **Environment** itself corresponds to an AWS account (and a region). So you can see the Organisation as a group of AWS account, hence the name of Organisation which reminds how customers already manage their fleet of accounts with AWS Organisation.

In my opinion, changing the name to Domain might negatively affect customers that are already using data.all (because they are used to this name, their data.all database is filled with objects using the "organisation" naming). Also, the team is currently focused on adding missing features and fixing the bugs we encounter.

However, if you believe that changing the name is important for your usage, then you can do it on your own branch. Maybe you can implement some king of "switch" that you can put in the config file. In this way, existing customers won't be affected, but new customers that prefer "Domain" over "Organisation" can edit the config to see the change appearing in the UI/database.

**Comment by pascalwhoop** [comment]
Alternatively how about adding a layer between the conceptual terms and the UI so that people can write whatever they want in a translation file? This may also be needed for internationalisation anyways since multi language support needs to disconnect UI code from UI strings. Then we could name the concept whatever we (or others) would want.

+=============================================================+
This email is confidential and may be privileged. If you have received 
it in error, please notify us immediately, delete the email, and do not 
copy it, disclose its contents or use it for any purpose.
+=============================================================+

**Comment by louishourcade** [comment]
Could be an option. Does it mean having a different name for the object in the UI (the name you set for your users) and the name of the database field (which remains "organization") ?

**Comment by pascalwhoop** [comment]
Yes that could be a way to do it indeed. One could also abstract the name in the data model to “org level 1-3”. But I think a default set of terms is also valid. 
We’re alternatively thinking to leverage a future i18n framework to map terms to the three levels. That may make the entire application quite customisable regarding strings while keeping companies able to stay in sync with upstream since the content is not interwoven with the code base.
