### ISSUE TITLE
How to best work together with this team while adapting it to make it our own

### ISSUE THREAD

**Issue by pascalwhoop** [awslabs/aws-dataall#52]
what's the teams recommended way to make data.all our own while still receiving upstream updates? 
Currently it's more of a boilerplate/quickstarter but ideally, we'd like to continue pulling in changes from upstream. However, that would require pretty big integration efforts from our side to merge in changes while also changing the theme, entity names (e.g. organisation/domain) etc. 

Any recommendations?

**Comment by louishourcade** [comment]
Hello,
Customers usually fork the awslabs/aws-dataall repository and create their own branch from which they deploy data.all in their AWS accounts. In this way, they can configure their data.all deployment in their custom branch, and receive updates by merging from the main branch.

This works well if you do not diverge to much from the open-source version (main branch). Customers that want to keep close to the main branch just have to change the **cdk.json** and **cdk.contect.json** files, which are the config files for the deployment.

However merge conflicts might appear if you start diverging form the open-source version (editing some functionalities, changing naming convention, ...). Here you have two solutions:
- Resolve potential conflicts when merging from the main branch
- Create a pull request to edit the main branch. If your change benefits other users (adding a new functionality for example), then the team will accept the merge and your version will be similar to the main branch again which means easier code merge for you.

If you need new data.all features and want to create them, I suggest that you create an Github Issue first, so that the data.all team is aware of what you are doing. This will help having your code integrated in the main branch.

I hope this answers your question.
