### ISSUE TITLE
datapolicy fails with maximum length exception while onboarding many env's

### ISSUE THREAD

**Issue by arjun-chopra** [awslabs/aws-dataall#553]
### Describe the bug

While onboarding a new env to data.all, each regions needs to be onboarded as separate env. While onboarding an env a new data policy is added as an inline policy to datallPivotRole.
Iam restricts inline policy to 10k length combined and which in turn causes CF stack to fail when trying to onboard 4+ env a.k.a regions to data.all. To mitigate that dataPolicy needs to be implemented using managed policy instead on inline policy.

### How to Reproduce

Onboard 5 diff regions to data.all the 5th region or subsequent region cannot be onboarded as the max policy length is 10K for inline policies.

### OS

Any

### Python version

3.9

### AWS data.all version

All

**Comment by arjun-chopra** [comment]
Fixed in PR - https://github.com/awslabs/aws-dataall/pull/552

**Comment by dlpzx** [comment]
Hi @arjun-chopra thanks for raising the issue and PR! I think you are right on converting the DataPolicy to a Managed Policy instead of an inline policy. Just bear in mind that it is not a policy that is added to the pivotRole, it is added to the environment roles. We are doing changes to the `DataPolicy` for V1.6.0 release in #462. To avoid merge conflicts, we should either 1) wait for v1.6.0 to be released (mid July) or 2) open the PR to v1m6m0 branch. Let me have a look and get back to you

**Comment by dlpzx** [comment]
After taking a look at your issue, the problem is not in the DataPolicy as this policy is not attached to the pivotRole. The root cause of the issue is that you are trying to create many environments (more than 5) in the same AWS account. Each environment created several custom resource Lambdas, each with a different dead letter queue (SQS, KMS). Data.all uses the built-in CDK constructs that grant additional permissions to the pivot role to these dead letter queues. Your issue is that by having multiple environments in the same account the amount of dead letter queues that the pivotRole gets access to increases as well as the pivotRole policy. In v1.6 we have simplified the dead letter queues resulting in policies that are significantly smaller, which will alleviate your problem. It won't solve the issue completely, maybe you reach limitations when you create X number of environments in the same account. I propose to wait until v1.6.0 is released and perform the test again to see what is the actual limitation and what is your requirement on number of environments per account.

**Comment by dlpzx** [comment]
It was alleviated in V1.6. It is not a priority at the moment but will be opened if requested again.
