### ISSUE TITLE
Request for share is being sent for invalid environment (CREATE_FAILED)

### ISSUE THREAD

**Issue by TejasRGitHub** [awslabs/aws-dataall#556]
### Describe the bug

When trying to create a draft for a dataset / Table/ Folder from the Catalog, on the "Request Access" Page, in the environment dropdown, an environment is being listed whose creation has failed at Cloudformation. A user is able to select this environment and also able to select the team and click "Send Request". This should be blocked as the environment's has a CREATE_FAILED status and is not a valid environment

Note - Although this request is shown as "Request Sent" on the Catalog Page when clicking "Send Request". When checked it on the Shares -> Sent page it doesn't appear there.

### How to Reproduce

1. Goto Catalog 
2. Select a dataset / table / folder, click on the request access button ( lock icon)
3. Select an environment which has status "CREATE_FAILED". ( Mock the status )
4. Select Team
5. Click on "Send Request" button. 

### Expected behavior

The environment whose creation has failed should not be listed in the environment's dropdown on the Request Access Page OR there should be some error message displayed when trying to send share request after pressing the "Send Request" button

### OS

Mac

### Python version

3.9

### AWS data.all version

1.5

**Comment by dlpzx** [comment]
Hi @TejasRGitHub, thanks for opening the issue. I think you have pointed at an issue that might affect other features as well. For example I just checked and it affects other actions such as creating a dataset or any other resource in an invalid environment. We will pick this up as soon as possible in the feature branch that is linked to this issue

**Comment by dlpzx** [comment]
Hi @TejasRGitHub, I'll be working on this issue.  These are some alternatives considered:
-> check the environment once the share request is open
-> list only the valid environments in frontend with a filter in list_environments or with a new api all in all. I am more inclined to the second approach. Have single-purpose api calls makes it easier to test and to understand.

I think the second option is better and it could be re-used in other elements. For example, for dataset creation. Steps for the implementation:
1. create a new api in core/environments 'list_valid_environments'
2. use 'list_valid_environments' instead of 'list_environments' when appropiate
3. add tests for the new api

Let me know if this sounds good with a 👍

**Comment by TejasRGitHub** [comment]
Hi @dlpzx , 

The second option seems fine to me. Yes, testing and implementing would be easier. 

The third option that you mentioned also seems interesting. Let me know if I get it right, on the frontend `listEnvironments` api, you will pass the filter for fetching only environments which are valid. Basically, this will involve modifying `query_user_environments` method in environment_service.py.

**Comment by TejasRGitHub** [comment]
Okay. Got it. In that case option two implementation seems to be a good choice

**Comment by dlpzx** [comment]
Merged and released with v2.1.0 🚀
