### ISSUE TITLE
Shared database naming format

### ISSUE THREAD

**Issue by anilprobable** [awslabs/aws-dataall#633]
Hi,
I have requirement for shared database name format.

1. AWS Account A, Having glue database name xyz
2. Through data.all, created dataset in data.all.
3. Through data.all raised dataset share request for another Account B.
4. database shared to Account B with name xyz_shared_asdfgh (random suffix generated by data.all)

Now, every time if we share same database due to some any reason, it creates with new name suffix - xyz_shared_**random**, and shared database name get change.

Is it possible if we can fix the **random** suffix part or eliminate, so that Account B having same consistent shared database name and this DB name  use in data pipeline or queries in Account B.
SO, if we change in shared database name or re-share same database, it should not impact any of data pipeline and queries.

**Comment by dlpzx** [comment]
Hi @anilprobable, thanks for raising the issue.  I understand your issue, given the current sharing we have:
Original database in AccountA: `database-accountA`
share1 (groupB1) database in AccountB: `database-accountA-shared-share1Uri`
share2 (groupB2) database in AccountB: `database-accountA-shared-share2Uri`
share12 (groupB1 has deleted and re-created a share) database in AccountB: `database-accountA-shared-share12Uri`

The reason to use a database dedicated to each share request is that the implementation is very clean. Once the share is revoked the created database can be deleted. It ensures that every share request is independent from each other. But you pointed out some of the disadvantages, plus some that I also think we can add:
- any application consuming `database-accountA-shared-share1Uri` depends on the suffix `shared-share1Uri` which can vary if the share is re-created. 
- Plus it is not known beforehand, pipeline development needs to be updated when the share is open.
- In addition we might end up with a lot of `database-accountA-shared-shareXUri` in the target account, which is a bit confusing.

### Alternatives
- Alternative 1: It can be argued that although the implementation is not so straightforward, we should implement the sharing based on one single `database-accountA-shared` database, without creating a database per share request. It is a re-design so it requires more development and testing of the share module.
- Alternative 2: your issue is in the naming of the database. A workaround would be to suffix the shared database name with something know like the requester name. Something like `database-accountA-shared-groupName` or `database-accountA-shared-consumptionRoleName`. It requires minimal changes in the sharing module, but we would need to see how it affects backwards compatibility.

At the moment we are working on a major release (V2.0.0) which will be available in the next weeks. We can consider this feature for Q3 if there is capacity, but we cannot commit at the moment. In case you want to work on it, we are more than happy to support you with the design, coding and testing.

**Comment by anilprobable** [comment]
Thanks @dlpzx 
Could you please suggest the change details for Alternative 2 option (or any minimum change), so that I can assess this to achieve the consistent database name in Account B.

**Comment by anilprobable** [comment]
HI @dlpzx Could you please suggest so that we can start looking it, on fixed shared database name in another account.

**Comment by dlpzx** [comment]
Hi @anilprobable, sorry for the late response. Here are some details and hints for alternative 2: renaming shared-db-name  as `database-accountA-shared-groupName` or `database-accountA-shared-consumptionRoleName` instead of using `shareUri` as suffix. I will add the paths for the files directly in the version 2 code as it will be released in the following days. This code is available in `main-v2` branch. We use a single function to build the Glue database name, so to implement alternative 2, you just need to change one line (line 85) in `backend/dataall/modules/dataset_sharing/services/share_managers/lf_share_manager.py` 

```
    def build_shared_db_name(self) -> str:
        """
        Build Glue shared database name.
        Unique per share Uri.

        Returns
        -------
        Shared database name
        """
        return (self.dataset.GlueDatabaseName + '_shared_' + self.share.shareUri)[:254]
```

Instead of the `self.share.shareUri` in `return (self.dataset.GlueDatabaseName + '_shared_' + self.share.shareUri)[:254]` we should write something like `return (self.dataset.GlueDatabaseName + '_shared_' + self.share.principalId)[:254]`

**Comment by anilprobable** [comment]
Thanks for update.
We changed the same in 3 files and now we are getting consistent shared database name.

Thanks

**Comment by anmolsgandhi** [comment]
Confirming with @dlpzx, looks like the issue has been resolved, closing the issue. Please feel free to reopen the issue if you still have any questions.

**Comment by anilprobable** [comment]
Yes.. this has been resolved.
