### ISSUE TITLE
Environment Delete - incomplete and the person who deleted it not able to complete the delete from data.all

### ISSUE THREAD

**Issue by manjulaK** [awslabs/aws-dataall#670]
### Describe the bug

We are seeing an issue where we were able to delete a environment but the delete seems to be incomplete however the user who orignially created the UI is not able to attempt re-delete as it shows access denied for the user,

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

Validation should be added to check and not allow user to perform incomplete deletes. All the deletion should happen as one transaction and in case it is not possible it should roll back. The user should be allowed to retry the delete from the UI without needing a backend solution

### OS

All

### Python version

3.1

### AWS data.all version

all

**Comment by noah-paige** [comment]
Thank you for calling this out! The check on whether the environment still has outstanding resources associated before deleting was originally happening only AFTER the removal of group permissions to the environment - allowing for scenarios of incomplete deletes and access management issues on the UI 

This issue was fixed in the mentioned PR #674 to first handle all checks before any delete operations

Closing this PR for now...
