### ISSUE TITLE
Share request failing for Granular Share Request on v.2.0 with Imported Dataset

### ISSUE THREAD

**Issue by TejasRGitHub** [awslabs/aws-dataall#672]
### Describe the bug

After importing a dataset ( from an existing S3 Bucket and CMK KMS Key ) with Granular Datasharing model, the share request fails with the following error eventhough the glue table exists and LF has given the pivotRole Full Permissions 

``Share Item huingea8 found on share request but its correspondent Glue table anushka_gs_imported_4 does not exist.``

### How to Reproduce

On the Producer Account -
Import a S3 Bucket into a Dataset ( with CMK KMS ) 
Start Crawler on the dataset and wait for the table to show up

On the consumer Account -
Create a share request for the above dataset from the Catalog
Go to the Shares Page, Add items in the share request and click submit

On Producer Account -
Approve the request

### Expected behavior

The share request items should show SHARE_SUCEEDED. With all the proper sharing of database and tables

### OS

Mac

### Python version

3.9

### AWS data.all version

2.0

**Comment by nikpodsh** [comment]
Hello @TejasRGitHub! Thanks for the interest in v2.0 😄 
Could you please confirm that you were using beta release branch (`modularization/beta-modularization`) for testing? If so, when it is a known issue and it has been fixed in #639 for `modularization-main`(the fix itself is here: https://github.com/awslabs/aws-dataall/pull/639/files#diff-63ffd4c7ddd250e41022eeb50bd40b9f36874f41ed49394deaaa4c115b1e498e)

**Comment by anushka-singh** [comment]
Hey @nikpodsh 
Yes, we were using beta release branch (modularization/beta-modularization) for testing?
We also communicated the issue with Noah who informed us about the issue being fixed in modularization-main in the commit you pointed. 
We then pulled in that only that one line change, but are still facing the same issue.

**Comment by noah-paige** [comment]
We have seen this issue of `Insufficent Permissions on GrantPermissions Operation` in a similar issue here

https://github.com/awslabs/aws-dataall/issues/588


Looking at this comment
https://github.com/awslabs/aws-dataall/issues/588#issuecomment-1647328030

Typical scenarios when this happens:

    SCPs that block certain RAM actions
    Missing RAM permissions in the data.all pivotRole
    Glue Catalog Settings blocking sharing

**Comment by noah-paige** [comment]
Thanks @TejasRGitHub  and @anushka-singh for opening this issue! 

Closing as of now since the above PRs should resolve any issues seen with sharing in data.all v2.0 beta code...

Please re-open or create a new issue if additional problems persist
