### ISSUE TITLE
Azure Ad as IdP

### ISSUE THREAD

**Issue by dosiennik** [awslabs/aws-dataall#68]
Hi,

  We are trying to use Azure AD as IdP for data.all. We configured Cognito accordingly. We are able to login with Azure AD and we are receiving the list of user groups. 

As far as we see for the groups, Azure AD returns just identifiers of the groups  as random strings (not the readable names) and the identifiers are displayed to the users in the UI which is not very user friendly.

We are curious how to handle it since we would like to see the group names in the UI instead. We were thinking about mapping the group ids to group names in the piece of logic inside Cognito pre-token generation trigger. There is one challenge though since the group name can change in Azure AD.  It will affects the values of the tags, policies etc.

 I think for the Cognito Groups it is not a challenge because the groups name can't be changed there.

Do you have any recommendation how it can be handled? Did you test data.all with other IdP provides?

**Comment by dlpzx** [comment]
Hi @dosiennik,

Did you follow the steps listed in the following guide?
[Azure+Active+Directory+Integration+with+Amazon Cognito+User+Pools.pdf](https://github.com/awslabs/aws-dataall/files/8999286/Azure%2BActive%2BDirectory%2BIntegration%2Bwith%2BAmazon.Cognito%2BUser%2BPools.pdf)

There is an step in which we need to map the attributes from Microsoft AD to Cognito ones. For groups we have to create a custom attribute.

**Comment by louishourcade** [comment]
Hello,
Quick note: in the guide [Azure+Active+Directory+Integration+with+Amazon Cognito+User+Pools.pdf](https://github.com/awslabs/aws-dataall/files/8999286/Azure%2BActive%2BDirectory%2BIntegration%2Bwith%2BAmazon.Cognito%2BUser%2BPools.pdf), the name of the custom attribute should be **saml.groups** instead of **groups**. Otherwise it will not work ([reference to the code](https://github.com/awslabs/aws-dataall/blob/7300220b4842247739d3fea0de2747498180dc14/backend/api_handler.py#L66))

And I also faced the same issue with Azure AD group ID. It seems it has been there for a while [(stackoverflow issue](https://stackoverflow.com/questions/59331693/azure-group-claim-returns-object-id-need-group-name)). As mentioned in this post, I believe the only way is to do what you mentioned, which is implementing some kind of logic that calls Microsoft Graph to map group ID with their name.

**Comment by dosiennik** [comment]
Hello,

  Thanks for the info  and links. Yeah we noticed it and named the attribute as the code expects. It is mapped correctly although as I mentioned group id is there not the name. Indeed it seems to be Azure's 'feature' ;)  Currently we are working on a piece of logic in the Cognito event to map ids to name before token is generated.

**Comment by dosiennik** [comment]
Sure thing, let's keep in touch on the topic.
