### ISSUE TITLE
CDK Policy For Least Permissions should be automatically linked vs manually uploaded today

### ISSUE THREAD

**Issue by manjulaK** [awslabs/aws-dataall#688]
Creating a CDK policy by manually uploading the CF stack is not ideal. Would it be possible to do this instead with a CDK command. Today when linking accounts if the least privilege policy for CDK Exec role needs to be used the user has to manually upload the CDK Exec Least privilege Policy template  from the UI, create the policy  through cloudformation and then use it . The request here is that user should be able to pick least privilege option and yet not have to upload the template for policy creating from the UI. The policy should be created and ready for use.

**Comment by dlpzx** [comment]
Hello @manjulaK, thanks for opening an issue! Could you be more specific? Which CDK policy in particular are you referring to?

**Comment by manjulaK** [comment]
@dlpzx  good point, added more details abive.

**Comment by dlpzx** [comment]
Hi @manjulaK , we can change the instructions and process to make the bootstraping process more programatic. Is that what you are referring to? instead of manually downloading the file, users could introduce temporary credentials and with a button data.all would run 'create cloudformation stack' with the CDK exec policy and then the `cdk bootstraping` using that policy. What do you think?

**Comment by manjulaK** [comment]
yes @dlpzx  that is what we want let me. know if you think this is a feature your team would want to work or if you want us to look into

**Comment by dlpzx** [comment]
@manjulaK , thanks for the quick reply. This feaature might affect our thread model. Let me review with our security lead and once we have a clearer view on the requirements we can decide who works on it

**Comment by zsaltys** [comment]
@dlpzx the main problem is that there's too many manual steps to onboard environments. We worked with some of our users through onboarding and they find it confusing what they have to do, what ID to put where and they keep making mistakes. We would like to make this process absolutely bullet proof so that it's impossible to make a mistake.

The first problem is that we require users to manually install CDKCustomPolicy stack. There's a nicer way to do this. One example I liked is on the grafana observability platform. They have a UI that looks like this:

![Screenshot 2023-09-12 at 12 22 07](https://github.com/awslabs/aws-dataall/assets/1583403/2026ac62-10a4-4b14-acfd-f01c4ce14d4c)

The button is a link like this: https://console.aws.amazon.com/cloudformation/home#/stacks/create/review?templateURL=https://grafanalabs-cf-templates.s3.us-east-2.amazonaws.com/cloudwatch-metrics/CloudWatch.json&stackName=GrafanaLabs-CloudWatch-Metrics&param_AccountID=arn:aws:iam::008923505280:root&param_ExternalID=782250

You can see they make the template public on S3 and automatically provide param values. This approach could be used for creating stacks instead of asking users to download them and upload them and fill in values themselves.

However even better would be to avoid having to do this at all via UI. Im hoping that if users have installed CDK then they could run another command to install the CDK custom IAM policy using CDK? Would that be possible?

**Comment by mourya-33** [comment]
@zsaltys, We are planning to have the policies created from command line as well including the bootstrap. The admin user running the bootstrap would still need to download the cloudformation file for policy creation, to the local environment and provide the local file path to the command.
