### ISSUE TITLE
Deleting existing dataset with outstanding share requests orphans dataset URI

### ISSUE THREAD

**Issue by rbernotas** [awslabs/aws-dataall#733]
### Describe the bug

We tried to delete an existing dataset which had outstanding share requests on it.  The delete was processed, but the dataset was not removed from the Catalog.  It still exists.  When selecting the dataset we get an orphaned URI error.  The dataset is not present in the "dataset" table.  But in the "dataset_table" table, there are still lots of references to this datasetUri.  This dataset was imported and there were a lot of tables pulled in as part of that import; all of them are still present in "dataset_table".

### How to Reproduce

Version:   v2.0.0-beta1

Import a dataset with tables.
Submit one or more share request(s) to that dataset with another user.
Try to delete the dataset.
Observe that the dataset delete is processed, but that the dataset is still present in the Catalog.
Select the dataset from the Catalog.
Observe the URI not found error "An error occurred (ResourceNotFound):  Resource Dataset with URI <URI_here> not found", as well as the orphaned URI in records in "dataset_table" table (potentially also other tables).

### Expected behavior

Deleting the imported dataset should either remove all references to that dataset URI (along with associated records in the database), or at least warn the user that they can not delete the dataset without first removing all share requests and other items which may prevent proper cleanup of the dataset.  From a usability perspective it would be preferred that the dataset delete handles all cleanup, without further manual intervention on the part of other users--perhaps the user deleting the dataset is shown all the items that would be removed in a confirmation dialog prior to confirming deletion.

### Screenshots

<img width="680" alt="Screenshot 2023-09-01 at 12 56 06 PM" src="https://github.com/awslabs/aws-dataall/assets/97474536/9f7ba371-ce39-4a32-adaf-7847e9ce094a">

### OS

n/a

### Python version

n/a

### AWS data.all version

v2.0.0-beta1

**Comment by noah-paige** [comment]
Hi @rbernotas - taking a look at the above issue you have mentioned and trying to reproduce it in an AWS Deployment of data.all working off of `main-v2` branch

I was wondering what was the status of the outstanding share in the above scenario? - Currently, if the share is in a Share Succeeded or Revoke state then the dataset should not be able to delete but in a draft or submitted state we still allow dataset deletion

I verified the above in my account but want to confirm the expected behavior with what happened on your end.

In terms of the orphaned catalog items, I will continue looking into this on my end as well. In my attempts to reproduce I have seen some similarly strange behavior leaving behind items in the open search catalog - will let you know what I find

**Comment by rbernotas** [comment]
Hi @noah-paige , thanks for your response.  After discussing this some more internally, we think that this happened because we scrubbed some of the dataset tables manually to fix an issue, but we never cleared up the Opensearch index.  Thanks for taking a look at the Opensearch-specific issue!  We will look for this in the upcoming 2.0 release.

**Comment by noah-paige** [comment]
Sounds good @rbernotas - I will proceed with closing this issue for now. Thanks again for raising the issue and please reach out if you run into any other
