### ISSUE TITLE
Pivot Yaml template file could not be found on Amazon S3 bucket

### ISSUE THREAD

**Issue by cfregly** [awslabs/aws-dataall#95]
### Describe the bug

An error occurred (AWSResourceNotFound) when calling GET_PIVOT_ROLE_TEMPLATE operation: Pivot Yaml template file could not be found on Amazon S3 bucket

### How to Reproduce

Pivot Yaml template file could not be found on Amazon S3 bucket

### Screenshots

<img width="1767" alt="image" src="https://user-images.githubusercontent.com/1438064/180093270-a2355f21-800a-4adf-b9cb-90281dcc5580.png">

### OS

Mac

### Python version

3.9

### AWS data.all version

latest

**Comment by dlpzx** [comment]
Hello @cfregly, Can you give more details on the user that was performing the action, the groups that it belongs to, organisation and organisation admin groups?

**Comment by ouchl** [comment]
> Hello @cfregly, Can you give more details on the user that was performing the action, the groups that it belongs to, organisation and organisation admin groups?

The pivot role template file is deployed by CDK. So the dev environment i.e. docker cannot find it.

**Comment by dlpzx** [comment]
Thank you @cfregly , so this is when you are working as a developer with the docker-compose deployment. Since you are not deploying anything, the developer environment has limitations, such as in this case when it tries to access resources that are available when you deploy data.all. 

There are a few options here:
- provide those resources in the AWS account whose credentials you are using (it is one of the requirements of the developer environment). These would include the yaml file and some secrets and parameters in Secrets Manager.
- deploy data.all and use the credentials for the infra account with docker

At the end, a local developer environment does not completely substitute data.all deployment
